name: Build Kernel gki
on:
  workflow_dispatch:
    inputs:
      KSU:
        description: KernelSU Support
        type: boolean
        default: false
        
jobs:
  build:
    runs-on: self-hosted
    steps:

    - uses: actions/checkout@v4
      with:
        show-progress: false
        fetch-depth: 1
        
    - name: Build Kernel
      run: |
        repo init --depth=1 -u https://android.googlesource.com/kernel/manifest -b common-android12-5.10
        repo --trace sync -c -j$(nproc --all) --no-tags --fail-fast
        if [ -d common ]; then
            rm -rf common
            git clone https://github.com/rufnx/android_kernel_common --depth=1 --single-branch -b nethunter-susfs common
        fi
        if [[ ${{ inputs.KSU }} == true ]]; then
            curl -LSs "https://raw.githubusercontent.com/pershoot/KernelSU-Next/dev-susfs/kernel/setup.sh" | bash -s
        fi
        LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
      working-directory: common_dir

    - name: Check Linux Version
      run: |
        strings out/*/dist/Image | grep "Linux version"
      working-directory: common_dir
        
    - name: Upload Output
      uses: actions/upload-artifact@v4
      with:
        name: ImageZip
        path: common_dir/out/*/dist/Image
